# Site
name: "Uwelllou"
title: "Uwelllou"
description: "Wellcome to my blog!"
logo: 'U.png'
favicon: 'U.png'
baseurl: 
google_analytics: 'G-1FJ57TRTLJ'
disqus: 'demowebsite'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Gsik:
    name: Ji won
    display_name: Gsik
    avatar: 'assets/image/avatar.png'
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: jwyoun0501@gmail.com
    Instargram: https://www.instagram.com/uwelllou/
    description: "Hello i'm Auth of this blog! here is Uwelllou's Instargram link!"
  Uwelllou:
    name: Ju hyeok
    display_name: Uwelllou    
    avatar: 'assets/image/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: pjhk0725@naver.com
    Instargram: https://www.instagram.com/uwelllou/
    description: ""

# comments
---
layout: default
comments: true
# other options
---

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown



kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Analytics
analytics:
  provider               : "google-gtag" # Google Analytics Registration false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "G-6XZ5P6FVKY"
    anonymize_ip         : # true, false (default)

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
